name: Android CI

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the main branch
      - '*'   # Also trigger CI on pushes to any branch
  pull_request:
    branches:
      - main  # Trigger CI on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run lint
        run: ./gradlew lintDebug --console=plain

      - name: Run unit tests
        run: ./gradlew testDebug

      # Add additional steps here as needed, such as deploying artifacts or publishing test results
