name: Android CI

on:
  push:
    branches: [ "*", "**/**" ]
  pull_request:
    branches: [ "*", "**/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GROUPUP_TOKEN: ${{ secrets.GROUPUP_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          Release Notes for v1.0.0:
          - Add feature X
          - Fix issue Y
        draft: false
        prerelease: false
